### ISSUE TITLE
Joining atom-ide-community?

### ISSUE THREAD

**Issue by aminya** [atom-community/zadeh#1]
We are interested in this project. I was wondering if you can join us in @atom-ide-community, so we can continue maintaining this cool package. 

@rajendrant

**Comment by rajendrant** [comment]
Hi Amin,

Sorry for delay.
Sure. Would like to join.
I see you have cloned my project and added more improvements.
I could contribute with more improvements if you have planned on.

Certainly more documentation and some screenshots could help new users get used to it.
I could work on that.

Let me know other features you had thought about too.

**Comment by aminya** [comment]
No worries! I will invite you to the organization, and you can transfer the repository there.


I made #6 to make your master branch the same as mine.

**Comment by rajendrant** [comment]
Thanks. I will work on some doc and screenshots.

**Comment by aminya** [comment]
Thank you! I sent your invitation. It should appear in your email inbox.

**Comment by aminya** [comment]
Welcome to @atom-ide-community 🚀

**Comment by rajendrant** [comment]
Just reopening this to get some more info.

What is the exact plan of using this package.
For example, to use it as part of atom fuzzy finder (ctrl-t)
The following line should be changed (I have some local changes of this)
https://github.com/atom/fuzzy-finder/blob/824f3bc4a0049baa734302528b9aea151b6cfde9/lib/fuzzy-finder-view.js#L90

**Comment by aminya** [comment]
Yes. Ultimately, we will use it there or anywhere it can benefit from.

I would like us to also try to fix #7 and #3 if possible.

**Comment by aminya** [comment]
Also, it would be nice to check how this library compares to https://github.com/atom/fuzzy-native

**Comment by rajendrant** [comment]
Right. I will work on those.
I think fuzzy-native is not an exact implementation of fuzzaldrin-plus. So it could give different matches that are less useful to users.
Will do more analysis on that.

I also had this grep-viewer atom package, that is a nice UI for ag/ripgrep tools. 
https://ibb.co/Jpywgc5
Its in my local package, I could upload it if you think it could garner interest.

**Comment by aminya** [comment]
Sure! That would be nice.

**Comment by rajendrant** [comment]
SG. Will do.
