### ISSUE TITLE
electron v9.35

### ISSUE THREAD

**Issue by UziTech** [atom-community/zadeh#46]
Looks like we will need electron v9.3.5 bindings soon

https://github.com/atom/atom/pull/21777

**Comment by aminya** [comment]
I don't think fuzzaldrin-plus-fast needs any change or even rebuilding, because it uses N-Api. Anyways, I will replace `electrion@7` with `electron@9` just in case soon.

https://github.com/atom-ide-community/fuzzaldrin-plus-fast/blob/a8fb4e6a86522094ee4dea6fd464e2250a7e282c/package.json#L14
