### ISSUE TITLE
A little slower in few of the cases in benchmark:regular

### ISSUE THREAD

**Issue by aminya** [atom-community/zadeh#7]
If the dataset is small this is not faster than the JavaScript version. It is better to detect this or fix it or call the JavaScript functions instead.

**Comment by rajendrant** [comment]
@aminya 
Can you share any specific example you tried that was slower ? 
I don't see this being noticeably slower than the JS version.
I added a small dataset(100 elements) and found it mostly equal (fast/slow in some cases) in a powerful desktop, normal laptop.

The worst I see is in a odroid singleboard computer.
As shown below, the slower cases are a few milliseconds off.
So, wondering if you had any inputs.

I will try this in raspberry PI to gauge things better.
Its likely creating threads for small dataset is slowing a bit, and I am fixing that.
 

odroid@odroid:~/fuzzaldrin-plus-fast$ npm run benchmarksmall

> fuzzaldrin-plus-fast@0.11.2 benchmarksmall /home/odroid/fuzzaldrin-plus-fast
> node benchmark/benchmark-small.js

====== Running test - query:nm ======
Elapsed time - fuzzaldrin-plus-fast: 8 ms vs. fuzzaldrin-plus: 7 ms
====== fuzzaldrin-plus-fast is SLOWER

====== Running test - query:npm ======
Elapsed time - fuzzaldrin-plus-fast: 7 ms vs. fuzzaldrin-plus: 19 ms

====== Running test - query:node ======
Elapsed time - fuzzaldrin-plus-fast: 8 ms vs. fuzzaldrin-plus: 15 ms

====== Running test - query:grunt ======
Elapsed time - fuzzaldrin-plus-fast: 6 ms vs. fuzzaldrin-plus: 3 ms
====== fuzzaldrin-plus-fast is SLOWER

====== Running test - query:html ======
Elapsed time - fuzzaldrin-plus-fast: 5 ms vs. fuzzaldrin-plus: 3 ms
====== fuzzaldrin-plus-fast is SLOWER

====== Running test - query:doc ======
Elapsed time - fuzzaldrin-plus-fast: 11 ms vs. fuzzaldrin-plus: 24 ms

====== Running test - query:cli ======
Elapsed time - fuzzaldrin-plus-fast: 8 ms vs. fuzzaldrin-plus: 5 ms
====== fuzzaldrin-plus-fast is SLOWER

====== Running test - query:js ======
Elapsed time - fuzzaldrin-plus-fast: 3 ms vs. fuzzaldrin-plus: 2 ms
====== fuzzaldrin-plus-fast is SLOWER

====== Running test - query:jas ======
Elapsed time - fuzzaldrin-plus-fast: 4 ms vs. fuzzaldrin-plus: 1 ms
====== fuzzaldrin-plus-fast is SLOWER

====== Running test - query:mine ======
Elapsed time - fuzzaldrin-plus-fast: 5 ms vs. fuzzaldrin-plus: 3 ms
====== fuzzaldrin-plus-fast is SLOWER

====== Running test - query:stream ======
Elapsed time - fuzzaldrin-plus-fast: 4 ms vs. fuzzaldrin-plus: 1 ms
====== fuzzaldrin-plus-fast is SLOWER

**Comment by aminya** [comment]
Could you share your benchmark code? Did you use https://github.com/atom-ide-community/fuzzaldrin-plus-fast/blob/master/benchmark/benchmark-small.js?

I don't think using a low-end processor helps here. You should run the tests on a regular desktop computer that replicates the real-world environment.

**Comment by rajendrant** [comment]
Yes. I used the benchmark-small.js which tests data-small.txt (that has 100 lines as input)
I will do more test with a regular desktop.

But after the below PR, filter() API is quite fast (and never slow in my laptop/desktop).
https://github.com/atom-ide-community/fuzzaldrin-plus-fast/pull/12

I will do similar changes for the other APIs (score, match).

**Comment by rajendrant** [comment]
Following is the output in normal desktop.

rajendrant@rajendrant2:~/lib/fuzzaldrin-plus-fast$ npm run benchmarksmall

> fuzzaldrin-plus-fast@0.11.2 benchmarksmall /home/rajendrant/lib/fuzzaldrin-plus-fast
> node benchmark/benchmark-small.js

====== Running test - query:nm ======
Elapsed time - fuzzaldrin-plus-fast: 0 ms vs. fuzzaldrin-plus: 1 ms

====== Running test - query:npm ======
Elapsed time - fuzzaldrin-plus-fast: 0 ms vs. fuzzaldrin-plus: 6 ms

====== Running test - query:node ======
Elapsed time - fuzzaldrin-plus-fast: 0 ms vs. fuzzaldrin-plus: 5 ms

====== Running test - query:grunt ======
Elapsed time - fuzzaldrin-plus-fast: 0 ms vs. fuzzaldrin-plus: 2 ms

====== Running test - query:html ======
Elapsed time - fuzzaldrin-plus-fast: 0 ms vs. fuzzaldrin-plus: 1 ms

====== Running test - query:doc ======
Elapsed time - fuzzaldrin-plus-fast: 1 ms vs. fuzzaldrin-plus: 9 ms

====== Running test - query:cli ======
Elapsed time - fuzzaldrin-plus-fast: 0 ms vs. fuzzaldrin-plus: 5 ms

====== Running test - query:js ======
Elapsed time - fuzzaldrin-plus-fast: 0 ms vs. fuzzaldrin-plus: 1 ms

====== Running test - query:jas ======
Elapsed time - fuzzaldrin-plus-fast: 0 ms vs. fuzzaldrin-plus: 2 ms

====== Running test - query:mine ======
Elapsed time - fuzzaldrin-plus-fast: 0 ms vs. fuzzaldrin-plus: 8 ms

====== Running test - query:stream ======
Elapsed time - fuzzaldrin-plus-fast: 0 ms vs. fuzzaldrin-plus: 0 ms

**Comment by aminya** [comment]
> But after the below PR, filter() API is quite fast (and never slow in my laptop/desktop).
#12 
> I will do similar changes for the other APIs (score, match).

Thank you! That's awesome!

Yes, I think by small I meant "regular". In some cases, the native algorithm is slower. For example, look at the 3rd, 4th, and 5th cases here:

```
======
Filtering 66672 entries for 'index' took 29ms for 6168 results (~10% of results are positive, mix exact & fuzzy)
Filtering 66672 entries for 'index' took 44ms for 6168 results (~10% of results are positive, Legacy method)
======
Filtering 66672 entries for 'indx' took 32ms for 6192 results (~10% of results are positive, Fuzzy match)
Filtering 66672 entries for 'indx' took 50ms for 6192 results (~10% of results are positive, Fuzzy match, Legacy)
======
Filtering 66672 entries for 'walkdr' took 25ms for 504 results (~1% of results are positive, fuzzy)
Filtering 66672 entries for 'walkdr' took 15ms for 504 results (~1% of results are positive, Legacy method)
======
Filtering 66672 entries for 'node' took 87ms for 65136 results (~98% of results are positive, mostly Exact match)
Filtering 66672 entries for 'node' took 70ms for 65136 results (~98% of results are positive, mostly Exact match, Legacy method)
======
Filtering 66672 entries for 'nm' took 91ms for 65208 results (~98% of results are positive, Acronym match)
Filtering 66672 entries for 'nm' took 62ms for 65208 results (~98% of results are positive, Acronym match, Legacy method)
======
Filtering 66672 entries for 'nodemodules' took 87ms for 65124 results (~98% positive + Fuzzy match, [Worst case scenario])
Filtering 66672 entries for 'nodemodules' took 103ms for 65124 results (~98% positive + Fuzzy match, [Mitigation])
Filtering 66672 entries for 'nodemodules' took 375ms for 65124 results (Legacy)
======
Filtering 66672 entries for 'ndem' took 86ms for 65124 results (~98% positive + Fuzzy match, [Worst case but shorter srting])
Filtering 66672 entries for 'ndem' took 215ms for 65124 results (Legacy)
======
Matching 66672 results for 'index' took 97ms (Prepare in advance)
Matching 66672 results for 'index' took 56ms (cache)
Matching 66672 results for 'index' took 78ms (legacy)
```

**Comment by rajendrant** [comment]
The latest code is pretty fast in majority of cases (and just one case is slightly slower which seems to be due to calling into native)

====== Running test - query:index ======
Elapsed time - fuzzaldrin-plus-fast: 37 ms vs. fuzzaldrin-plus: 78 ms
length 6168 66672

====== Running test - query:indx ======
Elapsed time - fuzzaldrin-plus-fast: 31 ms vs. fuzzaldrin-plus: 82 ms
length 6192 66672

====== Running test - query:walkdr ======
Elapsed time - fuzzaldrin-plus-fast: 28 ms vs. fuzzaldrin-plus: 25 ms
length 504 66672
====== fuzzaldrin-plus-fast is SLOWER

====== Running test - query:node ======
Elapsed time - fuzzaldrin-plus-fast: 61 ms vs. fuzzaldrin-plus: 202 ms
length 65136 66672

====== Running test - query:nm ======
Elapsed time - fuzzaldrin-plus-fast: 58 ms vs. fuzzaldrin-plus: 213 ms
length 65208 66672

====== Running test - query:nm ======
Elapsed time - fuzzaldrin-plus-fast: 60 ms vs. fuzzaldrin-plus: 183 ms
length 65208 66672

====== Running test - query:nm ======
Elapsed time - fuzzaldrin-plus-fast: 59 ms vs. fuzzaldrin-plus: 181 ms
length 65208 66672

====== Running test - query:ndem ======
Elapsed time - fuzzaldrin-plus-fast: 62 ms vs. fuzzaldrin-plus: 380 ms
length 65124 66672

Matching 66672 results for 'index' took 325ms (Prepare in advance)
Matching 66672 results for 'index' took 327ms (cache)
Matching 66672 results for 'index' took 127ms (legacy)

**Comment by aminya** [comment]
Great work! 🚀  I haven't checked the code. Do we still support all the API of the legacy library?

**Comment by aminya** [comment]
Should we close this? Can we do anything about that remaining case? The difference is negligible when we consider the boost that we get in other cases.
```
====== Running test - query:walkdr ======
Elapsed time - fuzzaldrin-plus-fast: 28 ms vs. fuzzaldrin-plus: 25 ms
length 504 66672
```

**Comment by aminya** [comment]
With my new changes in #37, #36, #35, etc. Finally, fuzzaldrin-plus-fast is faster in all cases. So, this can be closed now. The few differences are random, and it is hard to see a meaningful difference.
